[package]
name = "noop-client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "noop-client"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["error-context", "help", "std", "usage", "env", "string", "derive"] }
openssl-sys = "0.9.102"
reqwest = { version = "0.12", features = ["json"] }
signal-hook = "0.3.17"
tokio = { version = "1", features = ["full"] }
