[package]
name = "noop-client"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "noop-client"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["error-context", "help", "std", "usage", "env", "string", "derive"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
scoped-pool = "1.0.0"
signal-hook = "0.3.17"
